### PR TITLE
Powerboost configuration

### PR DESCRIPTION
**Pull request by nanomad**
Thanks to @rubens73 for the powerboost implementation

This fixes https://github.com/cliviu74/wallbox/issues/32

### CODE REVIEW

**Comment by tmenguy** [comment]
Hi @nanomad , I took the liberty to add your schedule and ICP power in https://github.com/cliviu74/wallbox/pull/34 .... as like you I was needing the schedule parts thanks a lot!

**Comment by nanomad** [comment]
No worries :)

Closing this one instead

**Comment by tmenguy** [comment]
As we are at it, what would be the best way to delete a schedule ?

**Comment by nanomad** [comment]
@cliviu74 Do you want me to split ICP and Schedule as well?

**Comment by cliviu74** [comment]
> @cliviu74 Do you want me to split ICP and Schedule as well?
> 
> You can review this indepenedtly from the time-out so that @tmenguy can then rebase his own on top of this

Hey, good catch, didn't even noticed there's another one in there.
Yes please, we need to have separate issues for each feature, ICP and Schedule, even if they seem related.

 The ICP one could be an issue as early tests on chargers that don't have an energy meter installed throw some weird errors from the Wallbox API.

**Comment by nanomad** [comment]
@cliviu74 Split into https://github.com/cliviu74/wallbox/pull/37

As far as I understand, we can probably feature wall this based on the product configuration API, altough I'd avoid having to call tow APIs just to update the ICP setting

**Comment by nanomad** [comment]
Looking at the WB status endpoint, we can probably feature gate this by looking at:
- status['config_data']['icp_max_current'] not None and > 0
- 'POWER_BOOST' in status['config_data']['plan']['features']

**Comment by cliviu74** [comment]
Upon more testing, I found the following
- on installations without a power diverter, this won't do anything. The upstream wallbox API will reply with a 400 message, other than that it seems pretty benign
- I can't verify this indeed has the intended behaviour (i.e. setting ICP Max Current) so I'll take your word for it  @nanomad 
- As this library is intended as a simple interface to the wallbox API, I think gating should be done upstream (i.e. Home Assistant integration?!)


Based on this, I'll merge as soon as comments on the code are fixed:

- @nanomad can you please add documentation for the setIcpMaxCurrent method to README.md?

**Review by cliviu74 — CHANGES_REQUESTED** [review]
Looks good, @nanomad can you please add the method description to README.md?!

**Comment by nanomad** [comment]
@cliviu74 README updated

**Comment by rubenms73** [comment]
> Thanks to @rubens73 for the powerboost implementation
> 
> This fixes #32

Hi @nanomad, my pleasure. My username is @rubenms73, though.

**Pull request merged**
